# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        12.0

# Cursor
cursor_shape          beam
cursor_beam_thickness 1.5
cursor_trail          3
cursor_trail_decay    0.1 0.4
cursor_trail_start_threshold 2

# Opacité
background_opacity 0.85
dynamic_background_opacity yes

# Pas de bip sonore, bip visuel
enable_audio_bell no
visual_bell_duration 0.1
visual_bell_color #f38ba8

# Pas de confirmation
confirm_os_window_close 0
paste_actions confirm-if-large

# Couleurs Catppuccin Mocha
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# Noirs
color0  #45475A
color8  #585B70

# Rouges
color1  #F38BA8
color9  #F38BA8

# Verts
color2  #A6E3A1
color10 #A6E3A1

# Jaunes
color3  #F9E2AF
color11 #F9E2AF

# Bleus
color4  #89B4FA
color12 #89B4FA

# Magentas
color5  #F5C2E7
color13 #F5C2E7

# Cyans
color6  #94E2D5
color14 #94E2D5

# Blancs
color7  #BAC2DE
color15 #A6ADC8

# Tabs
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #1E1E2E
active_tab_background   #CBA6F7
inactive_tab_foreground #CDD6F4
inactive_tab_background #313244

# Divers
scrollback_lines 10000
enable_audio_bell no
window_padding_width 8

# Ligatures
font_features JetBrainsMonoNFM-Regular +liga +calt
font_features JetBrainsMonoNFM-Bold +liga +calt
font_features JetBrainsMonoNFM-Italic +liga +calt
font_features JetBrainsMonoNFM-BoldItalic +liga +calt


shell tmux new-session

