exec-once = waybar > /dev/null 2>&1
exec-once = dunst
exec-once = swaybg -i /home/jo/Pictures/Wallpapers/catppuccin-mocha.png -m fill
exec-once = hypridle
exec-once = wlsunset -l 47.9 -L 2.3 -t 3500 -T 6500
