input {
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        drag_lock = true
        scroll_factor = 0.5
    }
}

plugin:touch_gestures {
    workspace_swipe_fingers = 3
    workspace_swipe_edge = false
}
