# Fenêtres flottantes
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(wlogout)$

# Tailles flottantes
windowrule = size 800 600, match:class ^(pavucontrol)$
windowrule = size 800 600, match:class ^(blueman-manager)$
windowrule = size 900 600, match:class ^(nm-connection-editor)$

# Centrer
windowrule = center on, match:class ^(pavucontrol)$
windowrule = center on, match:class ^(blueman-manager)$
windowrule = center on, match:class ^(nm-connection-editor)$

# Opacité
windowrule = opacity 0.85 override 0.85 override, match:class ^(kitty)$
windowrule = opacity 0.95 override 0.95 override, match:class ^(thunar)$

# Workspace par défaut
windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 2, match:class ^(brave-browser)$
windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 2, match:class ^(google-chrome)$
windowrule = workspace 3, match:class ^(code-oss)$
windowrule = workspace 4, match:class ^(thunar)$
windowrule = workspace 5, match:class ^(betterbird)$
windowrule = workspace 6, match:class ^(onlyoffice-desktopeditors)$
windowrule = workspace 7, match:class ^(remmina)$

# Wlogout plein écran
windowrule = fullscreen on, match:class ^(wlogout)$

